---
title: "viz part 1"
author: "Yuxuan Du"
date: "2023-09-28"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```
load the data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

make a plot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

pipes and stuff
```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

gg_nyc_weather = 
  weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

## Fancy plot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```

plot with facets

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

try different variables
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .3) +
  geom_smooth() + 
  facet_grid(. ~ name)

```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```


```{r}
weather_df |>
  filter(name == "Molokai_HI") |>
  ggplot(aes(x = date, y = tmax))+
  geom_line()
```
## univariate plotting
```{r}
ggplot(weather_df, aes(x = tmax, fill = name))+
  geom_histogram(position = "dodge")

ggplot(weather_df, aes(x = tmax, fill = name))+
  geom_density(alpha = .3, adjust = .75)
```


using box plots
```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_boxplot()
```

violin plots

```{r}
ggplot(weather_df, aes(y = tmax, x = name)) +
  geom_violin(aes(fill = name), alpha = .5)
```

ridge plot
```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```

## class assessment
```{r}

```